
spring:
    h2.console:
        enabled: true
        path: '/console'
    datasource:
      url: 'jdbc:h2:file:C:/Users/dtrza/Desktop/todo-app/todo-app/todo-db'
      task.allowMultipleTasksFromTemplate: false

    jpa:
      hibernate:
        ddl-auto: create-drop

#server:
#  port: 8081